# Generated by Django 4.1.7 on 2024-04-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0067_lancamento_n_parcelas_lancamento_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordado',
            name='codigo',
            field=models.CharField(default='', max_length=50, verbose_name='código'),
        ),
    ]
