# Generated by Django 4.1.7 on 2024-04-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0068_bordado_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bordado',
            options={'ordering': ['nome', 'codigo'], 'verbose_name': 'Bordado'},
        ),
        migrations.AlterUniqueTogether(
            name='bordado',
            unique_together={('nome', 'codigo', 'cliente')},
        ),
    ]
