# Generated by Django 4.1.7 on 2024-04-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0069_alter_bordado_options_alter_bordado_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordado',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='código'),
        ),
    ]
