# Generated by Django 4.1.7 on 2024-04-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0071_cliente_cep_cliente_cidade_cliente_complemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
    ]
