# Generated by Django 4.1.7 on 2024-04-07 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0074_alter_cliente_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj2',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='CNPJ (dígitos)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj4',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='CNPJ (filial)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj9',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)], verbose_name='CNPJ (raiz)'),
        ),
    ]
