# Generated by Django 4.1.7 on 2024-04-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0075_alter_cliente_cnpj2_alter_cliente_cnpj4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComunicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de comunicação',
                'verbose_name_plural': 'Tipos de comunicação',
                'db_table': 'po2_tipo_comunicacao',
            },
        ),
    ]
