# Generated by anselmo 2024-04-08 18h46

from django.db import migrations


def do(apps, schema_editor):
    TipoComunicacao = apps.get_model("bordado", "TipoComunicacao")
    for tipo in ["WhatsApp", "E-mail", "Telefone"]:
        tipo_comunicacao = TipoComunicacao(
            descricao=tipo,
        )
        tipo_comunicacao.save()


def undo(apps, schema_editor):
    TipoComunicacao = apps.get_model("bordado", "TipoComunicacao")
    TipoComunicacao.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0076_tipocomunicacao'),
    ]

    operations = [
        migrations.RunPython(do, undo),
    ]
