# Generated by Django 4.1.7 on 2024-04-08 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0077_insert_tipo_comunicacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocomunicacao',
            options={'ordering': ['id'], 'verbose_name': 'Tipo de comunicação', 'verbose_name_plural': 'Tipos de comunicação'},
        ),
    ]
