# Generated by Django 4.1.7 on 2024-04-08 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0078_alter_tipocomunicacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranca',
            name='comunicacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='bordado.tipocomunicacao'),
        ),
    ]
