# Generated by Django 4.1.7 on 2024-04-09 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0080_set_cobranca_comunicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='comunicacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bordado.tipocomunicacao'),
            preserve_default=False,
        ),
    ]
