# Generated by Django 4.1.7 on 2024-04-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0081_alter_cobranca_comunicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
