# Generated by Django 4.1.7 on 2024-04-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0082_alter_cobranca_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cobranca',
            old_name='tipo',
            new_name='informacao',
        ),
    ]
