# Generated by Django 4.1.7 on 2024-04-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0083_rename_tipo_cobranca_informacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
