# Generated by Django 4.1.7 on 2024-04-10 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0084_cliente_bairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comunicacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bordado.tipocomunicacao', verbose_name='Comunicação preferêncial'),
        ),
    ]
