# Generated by anselmo 2024-04-08 20h55
import random

from django.db import migrations


def do(apps, schema_editor):
    TipoComunicacao = apps.get_model("bordado", "TipoComunicacao")
    tipos_comunicacao = TipoComunicacao.objects.all()

    Cliente = apps.get_model("bordado", "Cliente")
    for row in Cliente.objects.all():
        tipo_comunicacao = random.choice(tipos_comunicacao)
        row.comunicacao = tipo_comunicacao
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0085_cliente_comunicacao'),
    ]

    operations = [
        migrations.RunPython(do),
    ]
