# Generated by Django 4.1.7 on 2024-04-10 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0086_set_cliente_comunicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comunicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bordado.tipocomunicacao', verbose_name='Comunicação preferêncial'),
        ),
    ]
