# Generated by Django 4.1.7 on 2024-04-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0087_alter_cliente_comunicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='parcelamento',
            field=models.CharField(default='', max_length=30, verbose_name='Parcelamento padrão'),
        ),
    ]
