# Generated by Django 4.1.7 on 2024-04-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0088_cliente_parcelamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='parcela',
        ),
    ]
