# Generated by Django 4.1.7 on 2024-04-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0089_remove_cliente_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='parcelamento',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Parcelamento padrão'),
        ),
    ]
