# Generated by Django 4.1.7 on 2024-04-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0090_alter_cliente_parcelamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('preferencial', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bordado.cliente')),
            ],
            options={
                'verbose_name': 'Contato',
                'db_table': 'po2_contato',
            },
        ),
    ]
