# Generated by Django 4.1.7 on 2024-04-15 20:59

import bordado.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0092_alter_contato_email_alter_contato_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='cliente',
            field=models.ForeignKey(default=bordado.models.Cliente.default_client_id, on_delete=django.db.models.deletion.CASCADE, to='bordado.cliente'),
        ),
    ]
