# Generated by Django 4.1.7 on 2024-04-15 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0093_alter_contato_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bordado.cliente'),
        ),
    ]
