# Generated by Django 4.1.7 on 2024-04-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0094_remove_cliente_boleto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Forma de pagamento',
                'verbose_name_plural': 'Formas de pagamento',
                'db_table': 'po2_forma_pagamento',
                'ordering': ['id'],
            },
        ),
    ]
