# Generated by Django 4.1.7 on 2024-04-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0094_alter_contato_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='boleto',
        ),
    ]
