# Generated by anselmo 2024-04-08 18h46

from django.db import migrations


def do(apps, schema_editor):
    FormaPagamento = apps.get_model("bordado", "FormaPagamento")
    nomes = [
        "Boleto",
        "Cheque",
        "Depósito",
        "Dinheiro",
        "Pix",
    ]
    for nome in nomes:
        forma_pagamento = FormaPagamento(
            nome=nome,
        )
        forma_pagamento.save()


def undo(apps, schema_editor):
    FormaPagamento = apps.get_model("bordado", "FormaPagamento")
    FormaPagamento.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0096_formapagamento'),
    ]

    operations = [
        migrations.RunPython(do, undo),
    ]
