# Generated by Django 4.1.7 on 2024-04-16 21:47

import bordado.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0097_insert_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='forma_pagamento',
            field=models.ForeignKey(default=bordado.models.FormaPagamento.default_id, on_delete=django.db.models.deletion.PROTECT, to='bordado.formapagamento', verbose_name='Forma de pagamento'),
        ),
    ]
