# Generated by Django 4.1.7 on 2024-04-17 16:50

import bordado.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0098_alter_cliente_comunicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='forma_pagamento',
            field=models.ForeignKey(default=bordado.models.forma_pagamento_default_id, on_delete=django.db.models.deletion.PROTECT, to='bordado.formapagamento', verbose_name='Forma de pagamento'),
        ),
    ]
