# Generated by Django 4.1.7 on 2024-04-16 22:12

import bordado.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0098_cliente_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comunicacao',
            field=models.ForeignKey(default=bordado.models.TipoComunicacao.default_id, on_delete=django.db.models.deletion.PROTECT, to='bordado.tipocomunicacao', verbose_name='Comunicação preferêncial'),
        ),
    ]
