# Generated by Django 4.1.7 on 2024-04-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0099_alter_cliente_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
