# Generated by Django 4.1.7 on 2024-04-17 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bordado', '0103_alter_cobranca_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
