# Generated by Django 4.1.7 on 2024-04-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0108_alter_lancamento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='conta_corrente',
            field=models.BooleanField(default=False, verbose_name='Financeiro tipo conta corrente?'),
        ),
    ]
