# Generated by Django 4.1.7 on 2024-04-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0109_alter_cliente_conta_corrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nf',
            field=models.BooleanField(default=True, verbose_name='Nota Fiscal por cobrança?'),
        ),
    ]
