# Generated by Django 4.2.11 on 2024-06-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0110_cliente_nf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
