# Generated by Django 4.2.11 on 2024-06-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0111_pedidoitem_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
