# Generated by anselmo 2024-06-01 15h17
from django.db import migrations


def do(apps, schema_editor):
    PedidoItem = apps.get_model("bordado", "PedidoItem")
    for row in PedidoItem.objects.all():
        row.data = row.inserido_em
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0112_alter_pedidoitem_data'),
    ]

    operations = [
        migrations.RunPython(do),
    ]
