# Generated by Django 4.2.11 on 2024-06-01 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0113_pedidoitem_set_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
