# Generated by Django 4.2.11 on 2024-06-01 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0114_alter_pedidoitem_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoitem',
            old_name='data',
            new_name='data_pedido',
        ),
    ]
