# Generated by Django 4.2.11 on 2024-06-01 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0115_rename_data_pedidoitem_data_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='data_pedido',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do pedido'),
        ),
    ]
