# Generated by Django 4.2.11 on 2024-06-04 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0116_alter_pedidoitem_data_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='data_pedido',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do pedido'),
        ),
    ]
