# Generated by Django 4.2.11 on 2024-06-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0117_alter_pedidoitem_data_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apelido_slug',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
    ]
