# Generated by Django 4.2.11 on 2024-06-05 19:48

from django.db import migrations
from django.utils.text import slugify


def generate_apelido_slugs(apps, schema_editor):
    Cliente = apps.get_model('bordado', 'Cliente')
    for cliente in Cliente.objects.all():
        cliente.apelido_slug = slugify(cliente.apelido)
        cliente.save()


def undo(apps, schema_editor):
    ...


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0118_cliente_apelido_slug'),
    ]

    operations = [
        migrations.RunPython(generate_apelido_slugs, undo),
    ]
