# Generated by Anselmo on 2024-06-06 20:16

from django.db import migrations


def limpa_codigo(apps, schema_editor):
    Bordado = apps.get_model('bordado', 'Bordado')
    for bordado in Bordado.objects.all():
        if bordado.codigo.strip() == '-':
            bordado.codigo = ''
            bordado.save()


def undo(apps, schema_editor):
    ...


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0119_cliente_inicializa_apelido_slug'),
    ]

    operations = [
        migrations.RunPython(limpa_codigo, undo),
    ]
