# Generated by Django 4.2.11 on 2024-06-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0120_bordado_limpa_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordado',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
