# Generated by Django 4.2.11 on 2024-08-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0121_alter_bordado_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fansasia',
            new_name='fantasia',
        ),
    ]
