# Generated by Django 4.2.11 on 2024-09-23 21:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0122_rename_fansasia_cliente_fantasia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375')), django.core.validators.MaxValueValidator(Decimal('1000000'))]),
        ),
    ]
