# Generated by Django 4.2.11 on 2024-09-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0123_alter_pedidoitem_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='observacao',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Observação'),
        ),
    ]
