# Generated by Django 4.2.11 on 2024-10-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0124_pedidoitem_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='cortesia',
            field=models.BooleanField(default=False),
        ),
    ]
