# Generated by Anselmo on 2024-10-20 20:16

from django.db import migrations


def liga_cortesia(apps, schema_editor):
    PedidoItem = apps.get_model('bordado', 'PedidoItem')
    for pedido_item in PedidoItem.objects.all():
        valor_zerado = (
            -pedido_item.ajuste ==
            pedido_item.quantidade *
            pedido_item.preco +
            pedido_item.programacao
        )
        if pedido_item.ajuste and valor_zerado:
            pedido_item.cortesia = True
            pedido_item.save()


def undo(apps, schema_editor):
    ...


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0125_pedidoitem_cortesia'),
    ]

    operations = [
        migrations.RunPython(liga_cortesia, undo),
    ]
