# Generated by Django 4.2.11 on 2024-10-20 17:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0126_pedidoitem_cortesia_from_valor_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='programacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1000000'))], verbose_name='Pogramação'),
        ),
    ]
