# Generated by Django 4.2.11 on 2024-10-20 17:06

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import o2lib.models.base


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bordado', '0127_alter_pedidoitem_programacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375')), django.core.validators.MaxValueValidator(Decimal('1000000'))])),
                ('inserido_em', models.DateTimeField(auto_now_add=True)),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bordado.cobranca')),
                ('inserido_por', models.ForeignKey(default=o2lib.models.base.logged_user, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bordado.lancamento')),
            ],
            options={
                'verbose_name': 'Pagamento-Cobrança',
                'verbose_name_plural': 'Pagamentos-Cobranças',
                'db_table': 'po2_pagamento_cobranca',
            },
        ),
    ]
