# Generated by Django 4.2.11 on 2024-10-20 17:34

import bordado.models.pagamento_cobranca
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import o2lib.models.base


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bordado', '0128_pagamentocobranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentocobranca',
            name='alterado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pagamentocobranca',
            name='alterado_por',
            field=models.ForeignKey(default=bordado.models.pagamento_cobranca.PagamentoCobranca.first_user, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagamentocobranca',
            name='inserido_por',
            field=models.ForeignKey(default=o2lib.models.base.logged_user, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
