# Generated by Django 4.2.11 on 2024-10-20 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0130_alter_pagamentocobranca_alterado_em_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagamentocobranca',
            unique_together={('pagamento', 'cobranca')},
        ),
    ]
