# Generated by Django 4.2.11 on 2024-12-15 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0131_alter_pagamentocobranca_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentocobranca',
            name='cobranca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='bordado.lancamento'),
        ),
    ]
